apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingressShim.defaultIssuerName }}
  annotations:
    helm.sh/hook: post-install
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.ingressShim.defaultIssuerName }}-account-key
    http01: {}
